cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<int:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<int:product_id>/', views.full_remove, name='full_remove'),
    path('add_one/<int:product_id>/', views.cart_add_one, name='add_one'),
]

ecommerce2/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'), 
    path('shop/', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    
    

search_app/urls.py
from django.urls import path
from . import views

app_name='search_app'

urlpatterns = [
    path('', views.searchResult, name='searchResult'),
]

shop/urls.py
from django.urls import path 
from . import views

app_name ='shop'

urlpatterns = [
    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail, name='ProdCatDetail'),
        
] 

cart/models.py
from django.db import models
from shop.models import Product


class Cart(models.Model):
    cart_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Cart'
        ordering = ['date_added']

    def __str__(self):
        return self.cart_id

class CartItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    active = models.BooleanField(default=True)

    class Meta:
        db_table = 'CartItem'

    def sub_total(self):
        return self.product.price * self.quantity

    def __str__(self):
        return self.product

search_app/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def get_url(self):
        return reverse('shop:products_by_category', args=[self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

class Product(models.Model):
    name = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'products'
        verbose_name_plural = 'products'

    def get_url(self):
        return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])
    
    def __str__(self):
        return '{}'.format(self.name)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Cart, CartItem
from django.core.exceptions import ObjectDoesNotExist

def _cart_id(request):
    cart = request.session.session_key
    if not cart:
        cart = request.session.create()
    return cart

def add_cart(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
    except Cart.DoesNotExist:
        cart = Cart.objects.create(
            cart_id = _cart_id(request)
            )
        cart.save(),
    try:
        cart_item = CartItem.objects.get(product=product, cart=cart)
        if cart_item.quantity < cart_item.product.stock:
            cart_item.quantity += 1
        cart_item.save()
    except CartItem.DoesNotExist:
        cart_item = CartItem.objects.create(
                    product = product,
                    quantity = 1,
                    cart = cart
            )
        cart_item.save
    return redirect('cart:cart_detail')

def cart_detail(request, total=0, counter=0, cart_items = None):
    try:
        cart = Cart.objects.get(cart_id=_cart_id(request))
        cart_items = CartItem.objects.filter(cart=cart, active=True)
        for cart_item in cart_items:
            total += (cart_item.product.price * cart_item.quantity)
            counter += cart_item.quantity
    except ObjectDoesNotExist:
        pass
    
    return render(request, 'cart.html', dict(cart_items = cart_items, total = total, counter = counter))
    

def cart_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 1:
        cart_item.quantity -= 1
        cart_item.save()
    else:
        cart_item.delete()
    return redirect('cart:cart_detail')

def cart_add_one(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    if cart_item.quantity > 0:
        cart_item.quantity += 1
        cart_item.save()
    return redirect('cart:cart_detail')

def full_remove(request, product_id):
    cart = Cart.objects.get(cart_id=_cart_id(request))
    product = get_object_or_404(Product, id=product_id)
    cart_item = CartItem.objects.get(product=product, cart=cart)
    cart_item.delete()
    return redirect('cart:cart_detail')

search_app/views.py
from django.shortcuts import render
from shop.models import Product
from django.db.models import Q


def searchResult(request):
    products = None
    query = None
    if 'q' in request.GET:
        query = request.GET.get('q')
        products = Product.objects.all().filter(Q(name__contains=query) | Q(description__contains=query))
    
    return render(request, 'search.html', {'query':query,'products':products})

shop/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Category,Product
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, EmptyPage, InvalidPage


def index(request):
    text_var = 'django web app'
    return HttpResponse(text_var)
     
def allProdCat(request, c_slug=None):
    c_page = None 
    products_list = None
    if c_slug!= None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products_list = Product.objects.filter(category=c_page, available=True)
    else:
        products_list = Product.objects.all().filter(available=True)
    # PAGINATOR CODE
    paginator = Paginator(products_list, 4)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage,InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/category.html', {'category':c_page,'products':products})


def ProdCatDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug, slug=product_slug)
    except Exception as e:
        raise e
    return render(request, 'shop/product.html', {'product':product})

cart/templates/cart.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %} 
        This is the shopping cart page. Proceed to review your item and place the order.
{% endblock %}
{% block title %}
    Shopping Cart - Online Store
{% endblock %}
{% block content %}
    {% if not cart_items %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center">
                    Your cart is empty.
                </h1>
                <br>
                <p class="text-center">Please Click <a href="{% url 'shop:allProdCat' %}">here</a> to continue shopping.</p>
            </div>
        </div>
    {% else %}
        <div>
            <div class="text-center">
                <br>
                <h1 class="text-center my_title">Your shopping cart:</h1>
                <br>
                <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-primary">Continue Shopping</a>
            </div>
        </div>
        <div class="row mx-auto">
            <div>
                <table class="table table-sm">
                    <thead>
                      <tr>
                        <th class="th">Items</th>
                      </tr>
                    </thead>
                    <tbody>
                    {% for cart_item in cart_items %}
                      <tr>
                        <th scope="row"></th>
                        <td><a href="cart_item.product.get_absolute_url"><img class="cart-image" src="{{cart_item.product.image.url}}" alt=""></a></td>
                        <td>
                            {{cart_item.product.name}}
                            <br>
                            SKU: {{cart_item.product.id}}
                            <br>
                            Unit Price: {{cart_item.product.price}}
                            <br>
                            Quantity: {{cart_item.quantity}} x {{cart_item.product.price}}
                            <br>
                            
                            <a href="{% url 'cart:full_remove' cart_item.product.id %}"><img class="smol-icon" src="{% static 'img/trash.svg'%}" alt="ecommerce"></a>&nbsp;
                            <a href="{% url 'cart:add_one' cart_item.product.id %}"><img class="smol-icon" src="{% static 'img/more.svg'%}" alt="ecommerce"></a>&nbsp;
                            <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><img class="smol-icon" src="{% static 'img/minus.svg'%}" alt="ecommerce"></a>&nbsp;
                        </td>
                        <td>
                            ${{cart_item.sub_total}}
                        </td>
                        {% if cart_item < cart_item.product.stock %}
                            <td>
                                <a href="{% url 'cart:add_one' cart_item.product.id %}" class=""></a>&nbsp;
                                <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fas fa-minus-circle"></i></a>&nbsp;
                                <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fas fa-trash"></i></a>&nbsp;
                            </td>
                        {% else %}
                        <td>
                            <a href="{% url 'cart:cart_remove' cart_item.product.id %}"><i class="fas fa-minus-circle"></i></a>&nbsp;
                            <a href="{% url 'cart:full_remove' cart_item.product.id %}"><i class="fas fa-trash"></i></a>&nbsp;
                        </td>
                        </td><td>
                        {% endif %}
                      </tr>
                    {% endfor %}
                    </tbody>
                  </table>
            </div>
            <div>
                <table class="table table-sm">
                    <thead>
                      <tr>
                        <th scope="col">Checkout</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Please review your shopping cart items before proceeding with payment.</td>
                      </tr>
                      <tr>
                        <td>Your total is <strong>${{ total }}</strong></td>
                      </tr>
                    </tbody>
                  </table>
                  <div>
                      <a href="{% url 'shop:allProdCat' %}" class="btn btn-secondary btn-primary">Continue Shopping</a>
                  </div>
            </div>
        </div>
        <br>
    {% endif %}
{% endblock %}

search_app/templates/search.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %} 
        Welcome to the NBA store where you can buy authentic get from your favourite teams.
{% endblock %}
{% block title %}
    Search - Online Store
{% endblock %}
{% block content %}
    <div>
        <p class="text-center my_search_text">You have searched for: <b>"{{ query }}"</b></p>
    </div>
    <div  class="container">
        <div class="row row-cols-2">
            {% for product in products %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4"> 
                <div class="card text-center" style="min-width: 18rem;">
                <!-- class="item-image-info" -->
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <div class="row ">
                            <div class="col">
                            <h4>{{product.name}}</h4>
                            <p>{{product.price}}</p>
                            <a class="btn btn-outline-warning" href="{% url 'cart:add_cart' product.id %}"> Add to Cart</a>
                    </div>
                </div>
            </div>
            </div>
            </div>
                {% empty %}
                <div class="row mx-auto">
                    <p class="text-center my_search_text">No results found.</p>
                </div>
            {% endfor %}
        </div>
    </div>  
{% endblock %}

shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
      <meta charset="utf-8" content="{% block metadescription %}{% endblock %}">
      <title>Eommerce Template
      </title>
      <link rel="stylesheet" href="{% static 'css/new.css' %}"> 
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    </head>
    <script>

    </script>
    <body>
        <div class="container">
            {% include 'header.html' %}
            {% block content %}
            {% endblock %}
        </div>
            {% include 'footer.html' %}
            
              <!-- JS, Popper.js, and jQuery -->
              <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
              <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
              <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
              
    </html>
    </body>

shop/templates/shop/category.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %} 
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
        Welcome to the NBA store where you can buy authentic get from your favourite teams.
    {% endif %}
{% endblock %}
{% block title %}
    {% if category %}
        {{ cateogry.name }} - NBA Store
    {% else %}
       See the NBA Store
    {% endif %} 
{% endblock %}
{% block content %}
    {% if category %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    
    <div class="row my_row_class">
        <div class="mx-auto">
            <p><a href="{% url 'shop:allProdCat' %}">All Products</a> | {{category.name}}</p>
        </div>
    </div>
    
    {% endif %}
    <div>
        {% if category %}
        <div>
            <h1 class="text-center">{{category.name}}</h1>
            <p class="text-center">{{category.description}}</p>
        </div>
    <!-- <img class="cat-image" src="{{category.image.url}}" alt="{{category.name}}"> -->
    </div>
    {% else %}
    <!-- <img src="{% static 'img/ecom.jpeg' %}" alt="Our Products Collection"> -->
    <div class="">
        <h1 class="center">Product Collection</h1>
        <p></p>
    </div>
        {% endif %}
    <div class="container-fluid">
        <div class="row mx-auto">
            {% for product in products.object_list %}
            <div class="my_bottom_margin col-9 col-sm-12 col-md-4 col-md-12 col-lg-4"> 
                <div class="card text-center" style="min-width: 18rem;">
                <!-- class="item-image-info" -->
                <a href="{{product.get_url}}"><img class="card-img-top my_image" src="{{product.image.url}}" alt="{{product.name}}"></a>
                    <div class="card-body">
                        <div class="row ">
                            <div class="col"> <h4>{{product.name}}</h4>
                                <p>${{product.price}}</p>
                                {% if product.stock <= 0  %}
                                <p><b>Out of Stock</b></p>
                            {% else %}
                                <a class="btn btn-outline-warning" href="{% url 'cart:add_cart' product.id %}"> Add to Cart</a>
                            {% endif %}</div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mx-auto">
        {% if products.paginator.num_pages > 1 %}
        <hr>
        <div class="text-center">
            {% for pg in products.paginator.page_range %}
                <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %}axctive{% endif %}">{{pg}}</a>
            {% endfor %}
        </div>
        {% endif %}
    </div>
{% endblock %} -->

shop/templates/shop/footer.html
<div class="footer">
    <p>&copy; Ecommerce. All Rights Reserved. </p>
</div>

shop/templates/shop/header.html
{% load static %}
<header>
    <center>
        <section>
        <!-- <a href="{% url 'shop:allProdCat' %}" ><img class="header-image" src="{% static 'img/compic.png'%}" alt="ecommerce"></a> -->
        <nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <nav class="navbar navbar-light bg-light">
                  <a class="navbar-brand" href="#">
                    <!-- <img class="" width="20" height="20" src="{% static 'img/monitor.svg' %}"> -->
                  </a>
                </nav>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'shop:allProdCat' %}">Shop <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'shop:allProdCat' %}">Option <span class="sr-only">(current)</span></a>
                </li>
                <!-- <li class="nav-item active">
                  <a class="nav-link" href="{% url 'shop:allProdCat' %}">Option 2 <span class="sr-only">(current)</span></a>
                </li> -->
                <!-- {% for cat in links %}
                <li class="nav-item active">
                  <a class="nav-link" href="{{cat.get_url}}">{{cat.name}} <span class="sr-only">(current)</span></a>
                </li>
                {% endfor %} -->
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Products
                  </a>
                  <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for cat in links %}
                    <a class="nav-link" href="{{cat.get_url}}">{{cat.name}} <span class="sr-only">(current)</span></a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                    
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Something else here</a>
                  </div>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'cart:cart_detail' %}"><img class="smol-icon" src="{% static 'img/cart.png' %}">({{item_count}})</a>
                </li>
                
                {% endif %}
                <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
                  {% csrf_token %}
        
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
                  <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
                </form>
           
              </ul>
              <div class="form-inline my-2 my-lg-0">        
              </div>
            </div>
          </nav>
          <h2 class="header"s></h2>
        </section>
    </center>
</header>

shop/templates/shop/navbar.html
<!-- 

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'shop:allProdCat' %}">Shop <span class="sr-only">(current)</span></a>
      </li>
      {% for cat in links %}
      <li class="nav-item active">
        <a class="nav-link" href="{{cat.get_url}}">{{cat.name}} <span class="sr-only">(current)</span></a>
      </li>
      {% endfor %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cart:cart_detail' %}">Cart<span class="sr-only">(current)</span></a>
      </li>
      <form class="form-inline my-2 my-lg-0" action="{% url 'search_app:searchResult' %}" method="get">
        {% csrf_token %}

        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
        <button class="btn btn-outline-warning my-2 my-sm-0" type="submit">Search</button>
      </form>
 
    </ul>
    <div class="form-inline my-2 my-lg-0"> -->

shop/templates/shop/product.html
{% extends "base.html" %}
{% load static %}
{% block metadescription %}
    {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ product.name}} - NBA Store
{% endblock %}
{% block content %}
    <div>
        <div>
            <p><a href="{{ product.category.get_url }}" class="btn btn-secondary btn-primary">{{ product.category }}</a>
        </div>
        <div>
            <br>
            <div class="item-image-info">
                <div>
                    <div>
                        <img class="product-image" src="{{product.image.url}}" alt="{{product.name}}">
                    </div>
                </div>
                <div>
                    <div class="">
                        <h1>{{product.name}}</h1>
                        <p>${{product.price}}</p>
                        <p>Product Description:{{product.description}}</p>
                        {% if product.stock <= 0  %}
                            <p><b>Out of Stock</b></p>
                        {% else %}
                            <a class="btn btn-outline-warning" href="{% url 'cart:add_cart' product.id %}"> Add to Cart</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}